In [2]:
import numpy as np

In [3]:
arr1 = np.array([[10,3,6,8,9],[8,9,4,7,3]])
arr2 = np.array([[66,74,98,58,9],[69,8,6,87,21]])

In [8]:
print(arr1)

[[10  3  6  8  9]
 [ 8  9  4  7  3]]


In [9]:
print(type(arr2))

<class 'numpy.ndarray'>


In [10]:
print(arr2[0:])

[[66 74 98 58  9]
 [69  8  6 87 21]]


In [11]:
print(arr2[1,2:4])

[ 6 87]


In [12]:
print(np.shape(arr2)) #rows,cloumn

(2, 5)


In [13]:
print(np.size(arr2))

10


In [14]:
print(np.ndim(arr2))

2


In [15]:
print(arr2.dtype)

int64


In [16]:
print(len(arr2)) #no of nedted values

2


In [17]:
print(np.add(arr1,arr2))

[[ 76  77 104  66  18]
 [ 77  17  10  94  24]]


In [18]:
print(np.concatenate([arr1,arr2])) #axis 1 for horizontal and 0 for vertical concatenation

[[10  3  6  8  9]
 [ 8  9  4  7  3]
 [66 74 98 58  9]
 [69  8  6 87 21]]


In [19]:
print(np.ndim(a))

0


In [20]:
print(np.hstack([arr1,arr2])) #horizontal stack

[[10  3  6  8  9 66 74 98 58  9]
 [ 8  9  4  7  3 69  8  6 87 21]]


In [23]:
a = np.array([20,50,65,45,58,87])
b = np.array_split(a,3)
print(b[0])
print(b)

[20 50]
[array([20, 50]), array([65, 45]), array([58, 87])]


In [26]:
c = np.array([20,50,65,45,58,87,87])
d = np.array([45,65,78,54,12,32,65])
e = np.array([[20,50,65],[45,58,87]])
print(np.append(c,90))
print(np.append(e,90))

[20 50 65 45 58 87 87 90]
[20 50 65 45 58 87 90]


In [31]:
print(c)
print(np.insert(c,[2,4],58)) #array,index,value

[20 50 65 45 58 87 87]
[20 50 58 65 45 58 58 87 87]


In [33]:
print(c)
print(np.sort(c))

[20 50 65 45 58 87 87]
[20 45 50 58 65 87 87]


In [35]:
print(c)
print(np.where(c == 65))
print(np.where(c % 2 == 0))

[20 50 65 45 58 87 87]
(array([2]),)
(array([0, 1, 4]),)


In [37]:
print(c)
print(np.sort(c))
print(np.searchsorted(c,45))

[20 50 65 45 58 87 87]
[20 45 50 58 65 87 87]
1


In [45]:
print(a)
print(b[0])
print(b)
print(np.add(arr1,arr2))
print(c)
print(np.sum(c))
print(np.min(c))
print(np.max(c))
print(np.size(c))
print(np.mean(c))
print(np.cumsum(c))
print(np.cumprod(c))


[20 50 65 45 58 87]
[20 50]
[array([20, 50]), array([65, 45]), array([58, 87])]
[[ 76  77 104  66  18]
 [ 77  17  10  94  24]]
[[ 76  77 104  66  18]
 [ 77  17  10  94  24]]
563
10
104
10
56.3
[ 76 153 257 323 341 418 435 445 539 563]
[               76              5852            608608          40168128
         723026304       55673025408      946441431936     9464414319360
   889654946019840 21351718704476160]


In [44]:
import numpy as np

# Initial arrays
arr1 = np.array([[10, 3, 6, 8, 9], [8, 9, 4, 7, 3]])
arr2 = np.array([[66, 74, 98, 58, 9], [69, 8, 6, 87, 21]])
print(arr1)
print(arr2)
# Print array type
print("Type of arr2:", type(arr2))

# Print entire arr2
print("\narr2[0:] (Full array):\n", arr2)

# Print specific slice of arr2
print("\narr2[1,2:4] (Slicing the second row, elements from index 2 to 4):", arr2[1, 2:4])

# Shape of arr2
print("\nShape of arr2 (rows, columns):", np.shape(arr2))

# Size of arr2 (total number of elements)
print("\nSize of arr2 (number of elements):", np.size(arr2))

# Number of dimensions of arr2
print("\nNumber of dimensions of arr2:", np.ndim(arr2))

# Data type of arr2 elements
print("\nData type of elements in arr2:", arr2.dtype)

# Length of arr2 (number of nested arrays/rows)
print("\nLength of arr2 (number of rows):", len(arr2))

# Concatenation of arr1 and arr2 vertically
concatenated = np.concatenate([arr1, arr2])
print("\nConcatenation of arr1 and arr2 (vertical concatenation):\n", concatenated)

# Splitting a 1D array a into 3 parts
a = np.array([20, 50, 65, 45, 58, 87])
b = np.array_split(a, 3)

# Print original array a
print("\nOriginal array a:", a)

# Print first part of split array
print("\nFirst part of split array b[0]:", b[0])

# Print all parts of split array
print("\nAll parts of split array b:", b)

# Element-wise addition of arr1 and arr2
added_arrays = np.add(arr1, arr2)
print("\nElement-wise addition of arr1 and arr2:\n", added_arrays)

# Define c as the result of added_arrays for further operations
c = added_arrays

# Sum of elements in c
print("\nSum of all elements in c:", np.sum(c))

# Minimum value in c
print("\nMinimum value in c:", np.min(c))

# Maximum value in c
print("\nMaximum value in c:", np.max(c))

# Size of c (total number of elements)
print("\nSize of c (number of elements):", np.size(c))

# Mean of elements in c
print("\nMean of elements in c:", np.mean(c))

# Cumulative sum of elements in c
print("\nCumulative sum of elements in c:", np.cumsum(c))

# Cumulative product of elements in c
print("\nCumulative product of elements in c:", np.cumprod(c))



[[10  3  6  8  9]
 [ 8  9  4  7  3]]
[[66 74 98 58  9]
 [69  8  6 87 21]]
Type of arr2: <class 'numpy.ndarray'>

arr2[0:] (Full array):
 [[66 74 98 58  9]
 [69  8  6 87 21]]

arr2[1,2:4] (Slicing the second row, elements from index 2 to 4): [ 6 87]

Shape of arr2 (rows, columns): (2, 5)

Size of arr2 (number of elements): 10

Number of dimensions of arr2: 2

Data type of elements in arr2: int64

Length of arr2 (number of rows): 2

Concatenation of arr1 and arr2 (vertical concatenation):
 [[10  3  6  8  9]
 [ 8  9  4  7  3]
 [66 74 98 58  9]
 [69  8  6 87 21]]

Original array a: [20 50 65 45 58 87]

First part of split array b[0]: [20 50]

All parts of split array b: [array([20, 50]), array([65, 45]), array([58, 87])]

Element-wise addition of arr1 and arr2:
 [[ 76  77 104  66  18]
 [ 77  17  10  94  24]]

Sum of all elements in c: 563

Minimum value in c: 10

Maximum value in c: 104

Size of c (number of elements): 10

Mean of elements in c: 56.3

Cumulative sum of elements in c: [ 76 

In [57]:
import statistics as stats
tabacco_consumption = np.array([40,50,60,90,90,40])
deaths = [100,120,130,140,140,90]
print(c)
print(np.mean(c)) #sum/no of values
print(np.sort(c)) #sorted values
print(np.median(c)) #middle value
print(stats.mode(c)) #repeated value
print(np.std(c)) # to check the data spread from the mean value, useful for quality check
print(np.var(c)) #sq of the std varaince
print(np.corrcoef([tabacco_consumption,deaths])) #how first thing realted with another, like o check the dependency

[ 200 5000 5000 6500 4500  580  320  870]
2871.25
[ 200  320  580  870 4500 5000 5000 6500]
2685.0
5000
2443.9488410152944
5972885.9375
[[1.         0.90546992]
 [0.90546992 1.        ]]
